### ISSUE TITLE
Colours very light

### ISSUE THREAD

**Issue by A333333** [martijnpoppen/leditbe#2]
Thank you for this app and your hard work, but if I select the darkest green as a solid color from the dots, it is very light green. Also the most dark orange selected from the dots is presented as nearly white at the ledring. Only red and blue selected from the dots is dark blue and red like it is suppose to be.
I set the brightness of the ledring to 2-3%. I use Homeypro with beta firmware 2.8.2. Are you aware of this?

**Comment by fellownet** [comment]
Yes, I'm aware of this. Thing is; I'm sending the color as returned from the Flow card directly to the screensaver engine. In order for me to mitigate this problem I need to do some sort of color correction first, which I guess is possible, so I've added it to the list of todo's ;)

**Comment by A333333** [comment]
Thank you for your answer. That is clear to me.

I have an suggestion: I want to color the ledring depending on a value:
Let’s say a value of 0-200 is a color of green(0-50)-yellow(51-100)-orange(101-150)-red(>151) lineair. To do so I have  to make a lot of flows. It would be nice to use a smarter way to  program this.

It might be an idea to implement this in an update..

Regards,

Adri

Verstuurd vanaf mijn iPhone X

Op 30 aug. 2019 om 18:55 heeft Fellownet <notifications@github.com> het volgende geschreven:

﻿

Yes, I'm aware of this. Thing is; I'm sending the color as returned from the Flow card directly to the screensaver engine. In order for me to mitigate this problem I need to do some sort of color correction first, which I guess is possible, so I've added it to the list of todo's ;)

**Comment by fellownet** [comment]
That's a very specific use case which would unfortunately only clutter the action cards for other users. I'm sorry, but I'm not going to implement that. The good news however is that the color correction has been added :) It's currently being reviewed by Athom and if deemed okay I'll release it somewhere next week.

**Comment by A333333** [comment]
It was only a suggestion. I am glad you worked on the color correction! I am waiting for the update to be released.

Thanks for your work!👍

Verstuurd vanaf mijn iPhone X

Op 4 sep. 2019 om 21:03 heeft Fellownet <notifications@github.com> het volgende geschreven:

﻿

That's a very specific use case which would unfortunately only clutter the action cards for other users. I'm sorry, but I'm not going to implement that. The good news however is that the color correction has been added :) It's currently being reviewed by Athom and if deemed okay I'll release it somewhere next week.
