### ISSUE TITLE
App transfer

### ISSUE THREAD

**Issue by martijnpoppen** [martijnpoppen/leditbe#4]
Hey,
I already sent you a message on the Homey community.
You asked if someone was willing to take over the development. 

I would like to take over this app.
If you want to transfer:

-  I'll send my Athom Id to you in a DM on the community
- Can you transfer this repo to me?
- I'll create a new community topic and let yours merge into the new one.

Let me know ! :D

**Comment by fellownet** [comment]
Thanks.
Transfer of repo is requested.
